### PR TITLE
Fix parenthesis position in submdspan

### LINKED ISSUE #367: Compilation error with submdspan in CUDA/HIP
A minor typo produces a compilation error when calling `submdspan` from a `layout_stride` in CUDA or HIP. Here is an example with [compiler explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:cuda,selection:(endColumn:1,endLineNumber:3,positionColumn:1,positionLineNumber:3,selectionStartColumn:1,selectionStartLineNumber:3,startColumn:1,startLineNumber:3),source:'%23include+%3Carray%3E%0A%23include+%3Chttps://raw.githubusercontent.com/kokkos/mdspan/single-header/mdspan.hpp%3E%0A%0Aint+main()+%7B%0A++std::array%3Cint,+9%3E+d%7B%0A++++0,+5,+1,%0A++++3,+8,+4,%0A++++2,+7,+6,%0A++%7D%3B%0A%0A++std::layout_stride::mapping%3Cstd::dextents%3Cint,+2%3E%3E+mapping(std::dextents%3Cint,+2%3E%7B3,+3%7D,+std::array%7B1,+3%7D)%3B%0A%0A++std::mdspan%3Cint,+std::dextents%3Cint,+2%3E,+std::layout_stride%3E+m(d.data(),+mapping)%3B%0A%0A++std::submdspan(m,+0,+0)%3B%0A%0A+return+0%3B%0A%7D%0A'),l:'5',n:'0',o:'CUDA+C%2B%2B+source+%231',t:'0')),k:46.53512993262753,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:nvcc111u1,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:cuda,libs:!(),options:'-std%3Dc%2B%2B17',overrides:!(),runtimeTools:!(),source:1,stdinPanelShown:'0',wrap:'1'),l:'5',n:'0',o:'Executor+NVCC+11.1.1+(CUDA+C%2B%2B,+Editor+%231)',t:'0')),header:(),k:53.46487006737247,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) with `nvcc <11.2.0`.

The typo locates in the file `submdspan_mapping.hpp`, I would propose the following fix
```diff
diff --git a/include/experimental/__p2630_bits/submdspan_mapping.hpp b/include/experimental/__p2630_bits/submdspan_mapping.hpp
index 2a2cdf7..f32ffc4 100644
--- a/include/experimental/__p2630_bits/submdspan_mapping.hpp
+++ b/include/experimental/__p2630_bits/submdspan_mapping.hpp
@@ -608,7 +608,7 @@ layout_stride::mapping<Extents>::submdspan_mapping_impl(
     (defined(__NVCC__) &&                                                      \
      (__CUDACC_VER_MAJOR__ * 100 + __CUDACC_VER_MINOR__ * 10) < 1120)
                       MDSPAN_IMPL_STANDARD_NAMESPACE::detail::tuple<decltype(detail::stride_of(slices))...>(
-                          detail::stride_of(slices)...).values)),
+                          detail::stride_of(slices)...)).values),
 #else
                       MDSPAN_IMPL_STANDARD_NAMESPACE::detail::tuple(detail::stride_of(slices)...)).values),
 #endif
```

### PR DESCRIPTION
**Pull request by tpadioleau**
Closes #367

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Comment by tpadioleau** [comment]
Btw, we have two ways to check if we have to workaround CTAD issues
- https://github.com/kokkos/mdspan/blob/771e3caee734114f728c4bd192198007b7037d6e/include/experimental/__p2630_bits/submdspan_mapping.hpp#L560-L563
- https://github.com/kokkos/mdspan/blob/771e3caee734114f728c4bd192198007b7037d6e/include/experimental/__p2630_bits/submdspan_mapping.hpp#L607-L612

Could we keep only one ?

**Comment by dalg24** [comment]
@nmm0 @crtrott plz review

**Comment by tpadioleau** [comment]
I would go for the safer solution 1.
https://github.com/kokkos/mdspan/blob/771e3caee734114f728c4bd192198007b7037d6e/include/experimental/__p2630_bits/submdspan_mapping.hpp#L560-L563

**Review by crtrott — APPROVED** [review]

**Review by crtrott — CHANGES_REQUESTED** [review]
Yeah Number one is fine

**Review by crtrott — APPROVED** [review]
Can be done in a follow up unifying the guard.

**Pull request merged**
