### PR TITLE
standard_layout_static_array: Added missing include file

### PR DESCRIPTION
**Pull request by amklinv-nnl**

### CODE REVIEW

**Comment by amklinv-nnl** [comment]
This issue is currently breaking [the stdBLAS build](https://github.com/kokkos/stdBLAS/pull/68/checks?check_run_id=2768267311)

**Comment by dalg24** [comment]
> This issue is currently breaking [the stdBLAS build](https://github.com/kokkos/stdBLAS/pull/68/checks?check_run_id=2768267311)

You might want to add a test to ensure it is not broken again in the future

**Comment by crtrott** [comment]
We can add the test later.

**Comment by mhoemmen** [comment]
@dalg24 wrote:
> You might want to add a test to ensure it is not broken again in the future

The plan is for the P1673 implementation to use `extents<>::size_type` everywhere, in case P0009 changes again ; - ) .

**Pull request merged**
