### PR TITLE
add CMakeUserPresets.txt to .gitignore

### PR DESCRIPTION
**Pull request by nmm0**

### CODE REVIEW

**Review by dalg24 — DISMISSED** [review]
I would only accept `CMakeUserPresets.json` if accepting anything at all
as usual, this is something you can deal with locally on your system on on a particular repo.

**Review by mhoemmen — CHANGES_REQUESTED** [review]
I'm with @dalg24 -- thanks for the contributions, though!

**Comment by nmm0** [comment]
> I would only accept `CMakeUserPresets.json` if accepting anything at all as usual, this is something you can deal with locally on your system on on a particular repo.

Hmm, we do already have IDE specific folders such as that for visual studio and the generic build folder already on there. I can change to just CMakeUserPresets.json but do you want me to also remove the existing IDE-specific ignores?

**Comment by mhoemmen** [comment]
> we do already have IDE specific folders such as that for visual studio and the generic build folder already on there

@dalg24 Those might just be for automated MSVC testing.  Do we have that somewhere?

**Review by crtrott — APPROVED** [review]

**Review by mhoemmen — APPROVED** [review]
I think this is fine.  Thanks for the contribution!

**Pull request merged**
